services:
  - type: web
    name: missav-stremio
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PUBLIC_URL
        value: https://missav-stremio.onrender.com
      - key: NODE_ENV
        value: production
